spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:postgresql://localhost:5432/neobank_reports
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: reporting-service
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'
#      spring.json.value.default.type: "com.neobank.audit.events.TransactionEvent"      
        