server:
  port: 8083
  

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/neobank_account
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
     
                
               
        
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      